Add year range filter to Entities
ecds/beckett-search-ui pull request #64
Opened 2023-03-08 04:30 UTC by sarastanton

This PR adds a UI component to filter by year range on the Entities Search Page. 

A few points to note:
* opted NOT to initialize with a default range (such as the min/max of all entities), as this filters out all entities with `null` year values in initial result list - but the min/max range of the _slider_ is based on min/max of all entities
* the range is technically 0 - 1988, as there are some entities with a year of `0` - this is why the slider shows such a narrow section for a range in, say, the 1900s

Related Trello card:
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;S4UGc3aC&#x2F;52-date-component">Date Component</a></blockquote>

**Visual changes**

![Screenshot 2023-03-07 at 9 44 49 PM](https://user-images.githubusercontent.com/20568337/223618540-0b7758a5-f0f3-4c87-9f4a-e46b529ba345.png)

2023-03-08 14:50 UTC, blms requested changes
Looking great so far! Glad you were able to figure out the routing, I know that is all structured a little strangely. The year range filter is working really well, and I love the slider.

A few notes:

- Can you run `npx eslint ./src/**/*.js ./src/**/*.jsx --fix`, then add the needed JSDoc comments and fix any other non-auto-fixable errors/warnings? (Only those that pertain to your changes, of course!)
  - I'd like to add a pre-commit hook to run this command automatically, but for now if you use VSCode I wrote up [some instructions](https://github.com/ecds/beckett-search-ui/tree/develop#code-style-and-linting) for how to catch these in the editor, so you don't have to run the command every time.
- I noticed that I seem to have to click "Reset Search" twice for it to take effect. You might be able to get a sense of what's going on here with logging in the `onClick` handler, in `routeToState`, and in some of the `useEffect` calls. I have a hunch it might be a little complex; if you can't get it working after an hour or so of work, please let me know and I'll take a look!
- I'm getting some console errors about the `min` prop of the slider being set to `null`, any idea what's going on there?
  - I'll ask Jay about those 0-value years; I have a feeling it's not intentional and a bug in the index.

2023-03-08 14:54 UTC, blms commented
One other comment:

> opted NOT to initialize with a default range (such as the min/max of all entities), as this filters out all entities with null year values in initial result list - but the min/max range of the slider is based on min/max of all entities

That makes sense to me, good call!

Eventually this date range facet will be hidden behind conditional facets, but I still think there will end up being entries without years, so definitely still the right call to keep the filter unset entirely by default.

2023-03-08 21:25 UTC, sarastanton commented
> Can you run `npx eslint ./src/**/*.js ./src/**/*.jsx --fix`, then add the needed JSDoc comments and fix any other non-auto-fixable errors/warnings? (Only those that pertain to your changes, of course!)
> * I'd like to add a pre-commit hook to run this command automatically, but for now if you use VSCode I wrote up [some instructions](https://github.com/ecds/beckett-search-ui/tree/develop#code-style-and-linting) for how to catch these in the editor, so you don't have to run the command every time.

Done 👍 

> * I noticed that I seem to have to click "Reset Search" twice for it to take effect. You might be able to get a sense of what's going on here with logging in the `onClick` handler, in `routeToState`, and in some of the `useEffect` calls. I have a hunch it might be a little complex; if you can't get it working after an hour or so of work, please let me know and I'll take a look!

As discussed, this seems to be an existing issue on the Entities Search page – moving it into its own [issue #66](https://github.com/ecds/beckett-search-ui/issues/66)


> I'm getting some console errors about the `min` prop of the slider being set to `null`, any idea what's going on there?

I think this was because the  aggregated `min` value from the API is 0 (at least with this current dataset), which is falsey (gotta love JavaScript!). I set a fallback of 1900 for the `min` year so that even if the `min` value is 0, the sliders will 1) have a non-`null` minimum value and 2) not have to display a ~2000 year range.

2023-03-09 17:37 UTC, blms approved these changes
Looks and works great! Did a little linting and made a quick cosmetic change, I think it's now ready to merge. 🚀 Nice work!

2023-03-09 20:00 UTC, merged